// <auto-generated />
using System;
using DoAn_Ecommerce.Areas.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAn_Ecommerce.Migrations
{
    [DbContext(typeof(DPContext))]
    [Migration("20201217144233_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.BinhLuanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NguoiBinhLuan")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SanPhamBinhLuan")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NguoiBinhLuan");

                    b.HasIndex("SanPhamBinhLuan");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.ChiTietHoaDonModel", b =>
                {
                    b.Property<int>("HoaDon")
                        .HasColumnType("int");

                    b.Property<int>("SanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuongMua")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HoaDon", "SanPham");

                    b.HasIndex("SanPham");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLapHD")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("TrangThaiGiaoHang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhachHang");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.LoaiSanPhamModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LoaiSP");
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.NguoiDungModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgaySinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuyenHan")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.SanPhamModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaLoai");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.TinTucModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDang")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDang");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.BinhLuanModel", b =>
                {
                    b.HasOne("DoAn_Ecommerce.Areas.Admin.Models.NguoiDungModel", "KhachHang")
                        .WithMany("lstBinhLuan")
                        .HasForeignKey("NguoiBinhLuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_Ecommerce.Areas.Admin.Models.SanPhamModel", "SanPham")
                        .WithMany("lstBinhLuan")
                        .HasForeignKey("SanPhamBinhLuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.ChiTietHoaDonModel", b =>
                {
                    b.HasOne("DoAn_Ecommerce.Areas.Admin.Models.HoaDonModel", "HD")
                        .WithMany("lstCTHD")
                        .HasForeignKey("HoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_Ecommerce.Areas.Admin.Models.SanPhamModel", "SP")
                        .WithMany("lstCTHD")
                        .HasForeignKey("SanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.HoaDonModel", b =>
                {
                    b.HasOne("DoAn_Ecommerce.Areas.Admin.Models.NguoiDungModel", "KH")
                        .WithMany("lstHoaDon")
                        .HasForeignKey("KhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.SanPhamModel", b =>
                {
                    b.HasOne("DoAn_Ecommerce.Areas.Admin.Models.LoaiSanPhamModel", "LoaiSanPham")
                        .WithMany("ltsSanPham")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAn_Ecommerce.Areas.Admin.Models.TinTucModel", b =>
                {
                    b.HasOne("DoAn_Ecommerce.Areas.Admin.Models.NguoiDungModel", "NhanVien")
                        .WithMany("lstTinTuc")
                        .HasForeignKey("NguoiDang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
